name: Frama-C
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install opam
        opam init -y
        opam install --deps-only frama-c
        opam install frama-c
        opam install why3 why3-ide alt-ergo
        why3 config detect
        why3 config list-provers
        
    - name: Run Frama-C
      run: frama-c -wp maxint.c